const swaggerJsdoc = require("swagger-jsdoc");
const swaggerUi = require("swagger-ui-express");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Contacts API",
      version: "1.0.0",
      description: "A simple Express.js API for managing contacts",
    },
    servers: [
      {
        url: "http://localhost:3000/api",
      },
    ],
    components: {
      schemas: {
        Product: {
          type: "object",
          properties: {
            contactId: {
              type: "integer",
              description: "The contact Id generated by the server.",
              example: 10,
            },
            name: {
              type: "string",
              description: "The contact name.",
              example: "Leanne Graham",
            },
            email: {
              type: "string",
              description: "The email address.",
              example: "Sincere@april.biz",
            },
            website: {
              type: "string",
              description: "The website.",
              example: "hildegard.org",
            },
            phone: {
              type: "string",
              description: "The phone number",
              example: "1-463-123-4447",
            },
            companyName: {
              type: "string",
              description: "The company name.",
              example: "Romaguera-Crona",
            },
          },
        },
      },
    },
  },
  apis: ["./src/routes/*.js", "./src/routes/products/*.js"],
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
  app.use("/api/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
};
